### ISSUE TITLE
Cellrank based integration

### ISSUE THREAD

**Issue by cnk113** [jranek/EVI#1]
Hello,

I was reading your preprint and code, I had a question on whether the Cellrank based integration is truly an "early" integration method. Since RNA velocity transition is computed on the reduced space you are effectively using a intermediate representation?

EDIT: To clarify, the moments (Ms) calculation is done in PCA space.

Best,
Chang

**Comment by jranek** [comment]
Hi Chang, 

Thank you for your question and clarification! Yes, you are correct. For CellRank, I think it's fair to say it's not truly an early integration method. You are computing an intermediate representation first. You construct a cell similarity graph with the expression data in PCA space and then compute the RNA velocity transition matrix by reweighting the edges of this graph according to the RNA velocity directionality prior to taking a weighted sum of the two. However, this is a bit different from the other intermediate integration approaches that first transform each individual modality into their own intermediate representations (cell similarity graphs or subspaces). 

Jolene

**Comment by cnk113** [comment]
Thanks for the clarification. Do you perhaps think or see in your analysis that the (1st and 2nd) moments and velocity to be pretty batch/sample specific (in terms of the scale, etc.)?

**Comment by jranek** [comment]
Yes, I do think that RNA velocity estimation is fairly sample-specific!
